eod_calculator:
  cron: "0 0 * * 1-5"  # Runs on every day-of-week from Monday through Friday at 6:00 PM
  class: "EodCalculatorJob"
  queue: default

monthly_average_calculator:
  cron: "5 18 * * 1"  # Runs every Monday at 6:05 PM
  class: "MonthlyAverageCalculatorJob"
  queue: default
